prom-mdm-converter:
  # Default values for prom-mdm-converter.
  # This is a YAML-formatted file.
  # Declare variables to be passed into your templates.

  replicaCount: 2

  # init containers
  genevaSecrets:
    mode: kvagent 
    manual: # Must prepopulate secret manually
      secretName: geneva-secret # Name of kubernetes secrets containing gcs.{crt,key}

  # See https://github.com/Hexadite/acs-keyvault-agent
  kvagent:
    image:
      repository: linuxgeneva-microsoft.azurecr.io/acskeyvaultagent
      tag: master_11
      pullPolicy: Always
    certsPath: /secrets/
    authorityServer: https://login.microsoftonline.com/
    vaultResourceName: https://vault.azure.net
    use_msi: true
    # Geneva MDM doesn't support intermediate CA certs in anything except for OnCert generated certs
    # don't download CA certs by default.
    download_cacerts: true

    # Put your cert name in the following line
    #################
    cert: pfx-wcd-mds-gcs-stg::cert.pem:key.pem
    #################
    # Put your Key Vault URL in the following line
    #################
    vault_base_url: https://wdatp-infra-key-vault.vault.azure.net/
    #################
    
    resources: {}

  image:
    repository: kubernetesshared.azurecr.io/shared/prom-mdm-converter
    tag: latest
    pullPolicy: Always
    pullSecret:
      create: False
      name: ""
      #registry: 
      #username:
      #password:

  nameOverride: ""
  fullnameOverride: ""

  mdm:
  # if userSecretFile is true, will create a secret object with local certificates (see readme)
  # If it is false, will use the keyvault agent to pull certificates directly from keyvault
    useSecretFile: false
    logLevel: Info
    endpoint: https://global.metrics.nsatc.net/
    # Put your account name in the following line
    #################
    account: WCDDEV
    #################
    certFile: /secrets/certs_keys/mdm-cert.pem
    keyFile: /secrets/certs_keys/mdm-key.pem
    source:
      environment: DefaultEnvironment
      role: DefaultRole
      roleinstance: DefaultRoleInstance
      #identity:

  converter:
    region: region
    underlay: underlay
    statsdEndpoint: localhost
    statsdPort: 8125
    statsdProtocol: tcp
    debugLogs: false
    # You can put a default Geneva namespace for the metrics
    # if not specified, the value 'prometheus' is used
    defaultMdmNamespace: microservices-academy

  service:
    type: ClusterIP
    port: 80

  internalPort: 8080

  resources: {}
    # limits:
    #  cpu: 100m
    #  memory: 128Mi
    # requests:
    #  cpu: 100m
    #  memory: 128Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}

# You can take a look at the following example as a reference on how to fill the rules section:
# https://msazure.visualstudio.com/KubernetesSharedTools/_git/prom-mdm-converter?path=%2Frules%2Fexample_geneva.yaml&_a=contents&version=GBmaster
  rules: |
    defaultMetricAllow: false
    defaultDimensionAllow: true
    startsWithFilters: 
    - wdatp
    metrics:
      pod:cpu_usage_percent_by_limit_scaled:
      pod:memory_usage_percent_by_limit_scaled:
      ALERTS:


